### ISSUE TITLE
Case sensitive file systems brake on require

### ISSUE THREAD

**Issue by ConjecturDev** [paymentwall/paymentwall-node#17]
Throughout the codebase several instances of require("") use lowercase filenames, even though the real filename has a capital letter in it. On macOS this is totally fine, since the fs is case insensitive. But on ubuntu which is case sensitive, we get the following error:

```
Error: Cannot find module './base'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/XXXXXX/node_modules/paymentwall/lib/Widget.js:3:12)
```

This at line 3 in Widget.js
`var Base = require('./base')`, should be `var Base = require('./Base')`

**Comment by liufanhhh** [comment]
thanks!
